### ISSUE TITLE
make created folder name more readable from "yo liferay-theme:layout"

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-js-themes-toolkit#101]
Feature enhancement:

Currently 'yo liferay-theme:layout" generates a folder with -layouttpl. To me it looked like a typo and if the tpl extension is still something needed in folder name then I was expecting something like -layout-tpl.

**Comment by wincent** [comment]
I don't know much about DXP but I think it might depend on the naming pattern based on what I see in `git grep layouttpl` ([here is a probably equivalent GitHub search](https://github.com/liferay/liferay-portal/search?q=layouttpl&unscoped_q=layouttpl)).

Some sample hits:

https://github.com/liferay/liferay-portal/blob/09230c4f8d5d08045c305c359ffb359d509320d0/portal-kernel/src/com/liferay/portal/kernel/model/Plugin.java#L32

https://github.com/liferay/liferay-portal/blob/ff9beb2b4c2c62ff14faf39f77d6039ebe292f8a/modules/apps/marketplace/marketplace-service/src/main/java/com/liferay/marketplace/util/ContextUtil.java#L61

https://github.com/liferay/liferay-portal/blob/65059440dfaf2b8b365a20f99e83e4cdb15478aa/modules/sdk/gradle-plugins/src/main/java/com/liferay/gradle/plugins/tasks/DirectDeployTask.java#L93

https://github.com/liferay/liferay-portal/blob/65059440dfaf2b8b365a20f99e83e4cdb15478aa/tools/servers/tcat/LiferayDeployerFactory.groovy#L52

https://github.com/liferay/liferay-portal/blob/ff9beb2b4c2c62ff14faf39f77d6039ebe292f8a/portal-impl/src/com/liferay/portal/tools/PluginsSummaryBuilder.java#L501

https://github.com/liferay/liferay-portal/blob/ff9beb2b4c2c62ff14faf39f77d6039ebe292f8a/portal-impl/src/com/liferay/portal/tools/PluginsGitSvnSyncer.java#L317

At least some of those make it look like changing the folder name would be a breaking change. I am going to close this in the spirit of spring-cleaning, and if my analysis turns out to be mistaken we can re-open it (FWIW, I agree that the name isn't super readable).
