### ISSUE TITLE
Provide working support for transpilation and ES6+ modules

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#110]
We currently support ES6 module transpilation through the `es2015hook`, but it's not straightforward what would be the best approach to set it up and use it inside a theme.

The goal of this issue is to clarify the existing support and/or update to use our newer npm-bundler for better frontend compatibility.

**Comment by yuchi** [comment]
👏  👏 

@crcarlo and I tried to make it happen on the actual implementation, but failed miserably.

**Comment by mwilliams2014** [comment]
@jbalsas any update on this for [LRDOCS-5649](https://github.com/jbalsas/liferay-docs/pull/36)

**Comment by mwilliams2014** [comment]
@jbalsas Any update on this? The Docker Support issue is closed and we are now on rc.3, so what do we need to wrap up this issue? Thanks!

**Comment by wincent** [comment]
Our first step is going to be to delete the hook package, because like @yuchi said, it "fails miserably". We're going to need to replace it with something else entirely, but in the meantime its continued existence is only going to cause confusion.

**Comment by jbalsas** [comment]
I think that we could follow a similar approach as we took for PostCSS... maybe bundle webpack/rollup/parcel or sth else and make it easy to get a set of generated bundled files that one can easily use in the theme.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
