### ISSUE TITLE
Discrepancy between Clay Design System Icons and generated theme.

### ISSUE THREAD

**Issue by sbaechler** [liferay/liferay-js-themes-toolkit#111]
The Clay design system uses svg sprites for its icons.

However, the CSS that is generated via the theme generator uses Fontawesome and Glyphicons.

Also, the Clay documentation provides only a Webpack configuration. But Liferay uses Gulp or Maven.

Please try to keep the two in sync. It is really difficult to build a component library otherwise.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
