### ISSUE TITLE
NPM update liferay-theme-tasks fails

### ISSUE THREAD

**Issue by LucyI** [liferay/liferay-js-themes-toolkit#123]
Receiving the "You are running old version of liferay-theme-tasks" warning. 

After running **gulp build** the warning displays these version numbers:
Current version: 8.0.0-rc.0 Latest version: 8.0.0-rc.1

But in the same theme folder, after running **gulp deploy** the warning displays these version numbers:
Current version: 1.5.0 Latest version: 8.0.0-rc.1

npm ls shows liferay-theme-tasks@1.5.0
**After running npm update liferay-theme-tasks -- ls still shows 1.5.0**

Windows 10 machine
node 6.9.4
generator-liferay-theme 8.0.0-rc.0
node-sass

**Comment by wincent** [comment]
@Lucyl: I think that in order to get an rc (release candidate) version you have to fully specify it (ie. `liferay-theme-tasks@8.0.0-rc.3` — or soon, `liferay-theme-tasks@8.0.0-rc.4`) because rcs are considered prerelease.

We're planning on releasing 8.0.0-rc.4 within the near future — probably within a week — so I'd suggest you try updating when that comes out and we'll see if this is still an issue.

**Comment by wincent** [comment]
8.0.0 went out to NPM earlier today so I am going to close this one but please comment if you're still having trouble and we can reopen it.
