### ISSUE TITLE
Capability to remove layouts or themes deployed with gulp from server

### ISSUE THREAD

**Issue by JosemariaMunoz** [liferay/liferay-js-themes-toolkit#236]
Based on [Liferay Theme Generator](https://dev.liferay.com/es/develop/tutorials/-/knowledge_base/7-0/themes-generator), and using to build [layouts](https://dev.liferay.com/es/develop/tutorials/-/knowledge_base/7-0/creating-layout-templates-with-the-themes-generator-0) and [themes](https://dev.liferay.com/es/develop/reference/-/knowledge_base/7-0/theme-gulp-tasks), could be a good idea add a **new feature that allows to remove layouts or themes from an App server**.

**Comment by wincent** [comment]
(Just to provide some additional color, relaying this from a chat thread...) one of the use cases for this would be: working from Liferay Developer Studio, with all the Gulp tasks integrated, once a theme or layout is developed, you can deploy it directly from the interface. While it is possible to "undeploy" a theme by deleting it from the filesystem (obviously this is system and version-dependent, but they wind up somewhere like `bundles/portal-7.0.x/osgi/war/`), it would be nice to be able to do the same from the interface.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
