### ISSUE TITLE
Font awesome is imported as a css file instead of scss

### ISSUE THREAD

**Issue by GianBe** [liferay/liferay-js-themes-toolkit#256]
This is probably not a bug but a suggestion.

Looking at a clean theme created with liferay theme gerator I noticed that font-awesome imported into base.scss with:

`@import url(font_awesome.css);`

This can cause a few inconveniences  because it does not expose all the useful mixin included in the mixins file in the font-awesome scss folder.

Since all the font-awesome files are `.scss` why not importing the `font_awesome.scss` in the `base.scss`?

cc @marcoscv-work @pat270

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
