### ISSUE TITLE
not able to `gulp upgrade:revert` twice from a theme that was `gulp upgrade` twice

### ISSUE THREAD

**Issue by john-co** [liferay/liferay-js-themes-toolkit#267]
*Steps to reproduce:*
1. npm install -g generator-liferay-theme@latest
2. `yo liferay-theme` for 7.0
3. `gulp upgrade`
4. Assert 7.1 liferayTheme
5. npm install lfieray-theme-tasks@next
6. `gulp upgrade`
7. Assert 7.2 liferayTheme
8. `gulp upgrade:revert`
9. Assert 7.1 liferayTheme
10. npm install liferay-theme-task@latest
11. npm install generator-liferay-theme@latest
12. Assert package.json contains v8.0.3 theme-tasks and tasks
13. `gulp upgrade:revert`

*Actual Result:*
liferayTheme version remains at 7.1. package.json contains v9.0.0-alpha.1 theme-tasks and tasks

*Expected Result:*
liferayTheme version is 7.0

I'm guessing maybe this is double revert not possible anymore since the user has to switch between v8 and v9?

But similarly, we used to test for double revert for 7.1 back to 6.2.  The first revert from 7.1 to 7.0 works but the 2nd revert from 7.0 to 6.2 doesn't update the liferayTheme versioning.

**Comment by mwilliams2014** [comment]
Interesting I didn't think you could do a double revert because the revert depends on the backup folder's contents. Once you upgrade and accept to overwrite the backup folder, I thought you could only revert to the previous version. We do have this note that I see could be misleading: 
```
Note: An upgraded theme can be restored to its original state by executing gulp upgrade:revert.
```
I really meant that it can be restored to it's original state before the previous upgrade. If you are able to double revert, please let me know and I'll update the docs to make that clear. Thanks!

**Comment by wincent** [comment]
I'll look into this but my possibly controversial opinion here is that there is no way the tool should have a `revert` functionality (or even a backup functionality) at all — code should be managed under a version control system, and if you want to revert it should be with `git checkout`, not `gulp upgrade:revert`. Unlike our solution, which only keeps one backup, a version control system can record the entire history of all changes, and you can revert to any point in time. I'd suggest that we would be better off removing the `revert` stuff, because as it exists it is just an incomplete implementation of an actual version control system.

cc @jbalsas: this is the issue that I was mentioning to you before.

**Comment by wincent** [comment]
I created https://github.com/liferay/liferay-js-themes-toolkit/pull/269 as a proof of concept for what I think we should do (that one targets the v9 series — ie. master — but I'd suggest we should do it for v8 as well).

**Comment by mwilliams2014** [comment]
I'll monitor https://github.com/liferay/liferay-js-themes-toolkit/pull/269 . If your suggestion is accepted, I'll update the docs to remove mention of the revert functionality.

**Comment by wincent** [comment]
@mwilliams2014: those PRs went in, so yes, we should remove mentions of reverting from the docs.
