### ISSUE TITLE
Scaffolding options for gulp

### ISSUE THREAD

**Issue by seanjgildea** [liferay/liferay-js-themes-toolkit#30]
Confusion coming from past theme development would be eased by having empty /templates and /js folders in the /src directory. Or even replicating the files that can be edited in those folders to speed customization.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
