### ISSUE TITLE
Error during build theme in Liferay

### ISSUE THREAD

**Issue by mfd** [liferay/liferay-js-themes-toolkit#339]
```
:themes:psdxpftl-theme:gulpBuildF:\dev\prj\plussell\themes\psdxpftl-theme\node_modules\liferay-theme-tasks\tasks\watch.js:23
const PASSES = Object.values(passes);
                      ^

TypeError: Object.values is not a function
```
Error

**Comment by wincent** [comment]
I suspect you're seeing this because you are using quite an old version of Node. Node has had `Object.values` [since v7](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/values), which [came out in 2016](https://nodejs.org/fa/blog/release/v7.0.0/). v7 itself is so old that it is [no longer maintained](https://nodejs.org/en/about/releases/), so I'd suggest that you update to a more recent Node version. In the meantime, however, we should probably do a runtime check and print a more helpful error message than this.

**Comment by wincent** [comment]
We'll close this on the assumption that moving to a more recent version of NodeJS addressed your issue. In the meantime, I created #343 so that we at least print a helpful message when we detect that we're running on and old version of NodeJS.
