### ISSUE TITLE
Running 'gulp deploy' doesn't correctly deploy a theme to docker containers in a DXP Cloud workspace 

### ISSUE THREAD

**Issue by timscottbell** [liferay/liferay-js-themes-toolkit#384]
One of our potential clients, Sky TV, is trying to follow documentation for how to build and deploy a theme in their provisioned DXP Cloud Liferay workspace. They are using this documentation: https://www.google.com/url?q=https://portal.liferay.dev/docs/7-1/tutorials/-/knowledge_base/t/creating-themes&sa=D&ust=1565105803963000&usg=AFQjCNEXoCZR_x0HKBfm4lrRVC5yVTGbog. 

However, they noticed that when trying to do a hot deploy using the command `gulp deploy` per the documentation, it doesn't deploy to the local docker containers. They are confused about the change in development workflow for a DXP Cloud workspace, that it doesn't work and that there is no documentation how to get this working correctly. For now, I've given them the workaround to use `blade gw deploy` for hot deploy which works fine.

I've asked Greg Amerson on the tooling team, as well as Travis Cory from GS, and they suggested opening an issue over here.

**Comment by travisrcory** [comment]
@timscottbell one idea for a workaround with be to use `gulp deploy --live` as described [here](https://github.com/liferay/liferay-js-themes-toolkit/tree/master/packages/liferay-theme-tasks#deploy)

**Comment by wincent** [comment]
So it seems we need to figure out whether this is "working as intended" (and therefore requires a doc update) or whether we should be making some change to make `gulp deploy` work out-of-the-box for local Docker containers.

My understanding is that there is [this code](https://github.com/liferay/liferay-js-themes-toolkit/blob/a908c4e577fa413023197e8cd88469f9413282eb/packages/liferay-theme-tasks/tasks/deploy.js#L57-L61) which will run `gulp deploy:docker` or `gulp plugin:deploy` depending on the answers you provider during theme creation.

> it doesn't deploy to the local docker containers

So what happens when they run `gulp deploy`? What is printed to the console? One question I have is whether the right branch of the `else` is being taken in the code I linked to above. One thing they could do is see whether `gulp build` and then `gulp deploy:docker` does the right thing (those are the steps that should be happening under the hood when you call `gulp deploy`); if it does, that means the wrong branch is being taken (at which point, I'd want to know how they answered [the questions](https://github.com/liferay/liferay-js-themes-toolkit/blob/a908c4e577fa413023197e8cd88469f9413282eb/packages/liferay-theme-tasks/plugin/lib/init_prompt.js#L128-L163) during theme creation, and what the resulting theme files looked like (especially the `package.json` and the `liferay-theme.json`).

**Comment by jbalsas** [comment]
Hey @david-truong, can you please take care of consolidating all the different data inputs so we can understand what's exactly missing and needed here?

**Comment by timscottbell** [comment]
```
{
  "LiferayTheme": {
    "deployPath": "/home/timothy/git-repos/skytvtrial/bundles/deploy",
    "themeName": "tims-theme",
    "deployed": false,
    "deploymentStrategy": "DockerContainer",
    "dockerContainerName": "dxpcloud_skytvtrial_liferay_1"
  }
}
```

I've manually edited the `liferay-theme.json` to contain these contents. I can see that the `deploy:docker` command is being called now, but I get this error:

```
[11:19:15] Starting 'deploy:docker'...
tar: /home/timothy/git-repos/skytvtrial/bundles/deploy: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
read unix @->/var/run/docker.sock: read: connection reset by peer

/home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/liferay-theme-tasks/tasks/deploy.js:46
				if (err) throw err;
				         ^

Error: spawnSync /bin/sh EPIPE
    at _errnoException (util.js:1022:11)
    at spawnSync (child_process.js:579:20)
    at Function.spawnSync [as sync] (/home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/cross-spawn/index.js:45:14)
    at /home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/liferay-theme-tasks/lib/util.js:65:23
    at Stream.<anonymous> (/home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/event-stream/index.js:345:20)
    at _end (/home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/through/index.js:65:9)
    at Stream.stream.end (/home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/through/index.js:74:5)
    at Pack.onend (/home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Pack.emit (events.js:208:7)
    at endReadableNT (/home/timothy/git-repos/skytvtrial/themes/tims-theme/node_modules/tar-stream/node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

I encourage you to get a provisioned dxp cloud workspace to test it out. In `dxpcloud-localdev.gradle`  there is a task called `deployToDxpCloudLocal` that handles hot deploy to the docker containers. So it is definitely operating differently than a regular liferay workspace.

Also, a lot of the questions didn't make sense in the context of DXP Cloud. For example, `Enter the path to your app server directory`. It's not really applicable here.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
