### ISSUE TITLE
Typo in Themelet prompt for Font Awesome and should Font Awesome be added in a themelet?

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-themes-toolkit#387]
When creating a themelet in the themes toolkit v9.3.0, it asks "Would you like to add Font Awesome to your theme?" It should say themelet in this case, and I'm not sure that you would want to include Font Awesome via a themelet. Shouldn't that be left up to the Theme?

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
