### ISSUE TITLE
Themelets shouldn't have to be published to npm to test locally

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-themes-toolkit#388]
When I globally installed my themelet with `npm link` and then tried to install it in my theme, it gives me a 404 error that it's not in the npm registry, which is true, but I didn't think it had to be published to test and install themelets locally. Did the behavior change? I know I was able to do this before.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
