### ISSUE TITLE
Invalid Regular Expression in splitWords

### ISSUE THREAD

**Issue by einsty** [liferay/liferay-js-themes-toolkit#392]
Running fresh install of v9.4.0 `yo liferay-theme` (and also tried on 9.3.0) got the prompt for "what would you like to call your theme"  entered a string and then the generator just hung.  Hit Ctrl-C and got the following.

```
SyntaxError: Invalid regular expression: /[ _-]|(?<=[a-z])(?=[A-Z])/: Invalid group
    at splitWords (/Users/orin/.nvm/versions/node/v8.9.4/lib/node_modules/generator-liferay-theme/generators/common/splitWords.js:16:21)
```

Running on Mac system.  
```
npm -v
6.11.3

yo --version
2.0.2

gulp -v
[16:08:40] CLI version 2.0.1


This version of the liferay-js-themes-toolkit (9.3.0)
can create a liferay-theme:app for Liferay DXP and Portal CE v7.2

```

**Comment by wincent** [comment]
Looks like your version of NodeJS is choking on the negative lookbehind. What version are you on?

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
