### ISSUE TITLE
LTS version of Node isn't supported by JS Themes Toolkit

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-themes-toolkit#407]
See thread in frontend-dev channel: https://liferay.slack.com/archives/C03CAD9EF/p1574745338057500 

LTS is now at 12.13.1: https://nodejs.org/en/ In our docs, we recommend to use the LTS version as it's the most stable: https://help.liferay.com/hc/en-us/articles/360028834632-Installing-the-Theme-Generator-and-Creating-a-Theme

We should update the supported Node version for the JS Toolkit to the latest LTS or higher. @wincent are there plans to do that?

**Comment by jbalsas** [comment]
We should updated the docs to specify which LTS version, which in this case would be 10.x.x. We support an active or maintained LTS, never said we supported the latest. 

That being said, we can keep this open to see what it takes to support `12.x`.

Also... you're saying `js-toolkit` but filing this in `js-themes-toolkit`, @mwilliams2014... can you clarify if you're referring to this toolkit or [the real js toolkit](https://github.com/liferay/liferay-js-toolkit)?

**Comment by mwilliams2014** [comment]
Updated to specify Liferay Themes JS Toolkit @jbalsas . If there are no plans to update soon, then I'll explicitly note we support 10.x. I'm just finding this information out now, so there was no way to account for it earlier. I'll take care of it now and add a note to all the theme gen docs. Thx!

**Comment by mwilliams2014** [comment]
@jbalsas is v 10.x supported for the themes js toolkit for portal 7.0, 7.1, and 7.2?

**Comment by jbalsas** [comment]
We have different versions of the js-themes-toolkit which might be supported on different versions of node.js. I think @wincent might be better suited to provide that information.

Addtionally, this could be an interesting topic for @john-co and @manoelcyreno to explore 😉

**Comment by mwilliams2014** [comment]
I've created https://issues.liferay.com/browse/LRDOCS-7495 to track the documentation updates. I'll note the supported versions once they are verified @wincent . Thanks @jbalsas

**Comment by wincent** [comment]
> I think @wincent might be better suited to provide that information.

So the challenge here is that every major version update to NodeJS is likely to break packages that involve native (compiled) components, and node-sass is a big culprit here. In the toolkit we use node-sass as a transitive dependency of gulp-sass. I (not infrequently) see people internally experience build failures because they've installed Node v12 but liferay-portal uses v10 — depending on the order they run commands in or whether they do things directly on the commandline via `yarn` or via Gradle, different versions end up getting used and everything explodes.

So I always recommend sticking to the same version of Node as is used in liferay-portal. But I think in the longer term we need to avoid native dependencies like the plague. [Dart Sass](https://sass-lang.com/dart-sass) looks like a promising option that might enable us to get away from node-sass, which is far and away the biggest cause of problems for us.

**Comment by wincent** [comment]
I created https://github.com/liferay/liferay-js-themes-toolkit/issues/408 to track moving to Dart Sass. Supposedly, we can configure [gulp-sass](https://www.npmjs.com/package/gulp-sass) to use a Dart Sass instead of node-sass.

**Comment by mwilliams2014** [comment]
Confirmed with Peter Shin, the latest supported versions are:

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
