### ISSUE TITLE
liferay-portal page configuration is broken after upgrading to master having previously deployed a 7.2 layout template

### ISSUE THREAD

**Issue by Tim-Cao** [liferay/liferay-js-themes-toolkit#416]
**Step to reproduce**
1. Create a 7.2 layout template via 9.4.3 Liferay theme generator.
2. Deploy to 7.2.10.1-SP1 + FP3.
3. Start server.
4. Create a new widget page based on new layout template.
5. Shutdown server.
6. Upgrade DB to master.
7. Start master.
8. Go to Page administration > Click configure of the new page

**Expected Results:**
The configuration page should display normally.

**Actual Results:**
The page broken. The console will throw the following error:
```
2019-12-13 02:13:50.772 ERROR [http-nio-8080-exec-1][JDBCExceptionReporter:234] Table 'fp3.LayoutSEOSite' doesn't exist
2019-12-13 02:13:50.777 ERROR [http-nio-8080-exec-1][DynamicIncludeUtil:81] com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
com.liferay.portal.kernel.exception.SystemException: com.liferay.portal.kernel.dao.orm.ORMException: org.hibernate.exception.SQLGrammarException: could not execute query
	at com.liferay.portal.kernel.service.persistence.impl.BasePersistenceImpl.processException(BasePersistenceImpl.java:446)
```

Reproduce on:
Tomcat 9.0.17 + MySQL 5.7. Portal master GIT ID: 7ce7ab20a3835fe3634c284e434a175a6dc0c95a.

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
