### ISSUE TITLE
Support `gulp kickstart` for local themes

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#47]
From [gulp kickstart a local theme?](https://github.com/liferay/liferay-theme-tasks/issues/78) by @budkin76

> I've been playing around with the Liferay gulp theme tasks and noticed that the kickstart task only has 3 options:
>
> 1. Search globally installed npm modules
> 2. Search npm registry (published modules)
> 3. Classic theme
>
> Has anyone considered adding a 4th option to input a path to a locally developed theme? That would be pretty helpful.

**Comment by wincent** [comment]
I'm wondering, would this be all that different from just copying the folder normally? What transformations or omissions would you expect to see applied to the copy of the theme?

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
