### ISSUE TITLE
Add proper outbound licensing

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#48]
We should mark all of our code with our proper outbound licensing header:

```
/**
 * © 2018 Liferay, Inc. <https://liferay.com>
 *
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */
```

While we work on this, it would be good to tackle the long-standing [Remove redundant license comments in built files](https://github.com/liferay/liferay-theme-tasks/issues/47) issue and maybe even take a look at ["Upgrade" Gulp Task: missing file headers in css.diff](https://github.com/liferay/liferay-theme-tasks/issues/44)

/cc @silverhook, any hints, comments? 😉

**Comment by silverhook** [comment]
In general the header looks good to me.

Using the [SPDX IDs](https://spdx.org/ids) and the [REUSE.software](https://reuse.software) best practices on \*GPL family code is also much easier than for MIT and BSD-\* family, because the copyright notice is not part of the actual license text.

So we just include that header and just save the [LGPL-2.1-or-later](https://github.com/spdx/license-list-data/blob/master/text/LGPL-2.1-or-later.txt) text into `LICENSE`, it would be perfect.

As for keeping the copyright and license notices in the minified version, we should keep it. If nothing else, to make sure our downstream can more easily comply with the license of our code.

But, unless I’m mistaken, _1)_ this repo includes (or at least depends on) 3rd party code, and _2)_ going with LGPL-2.1-or-later would in fact be a license change for at least part of the code, which seems to be under MIT so far. If so, I would need to dig in a bit more. But it doesn’t look like a complex beast :)

**Comment by silverhook** [comment]
In general the header looks good to me, but do read on.

Using the [SPDX IDs](https://spdx.org/ids) and the [REUSE.software](https://reuse.software) best practices on \*GPL family code is also much easier than for MIT and BSD-\* family, because the copyright notice is not part of the actual license text.

So we just include that header and just save the [LGPL-2.1-or-later](https://github.com/spdx/license-list-data/blob/master/text/LGPL-2.1-or-later.txt) text into `LICENSE`, it would be perfect.

As for keeping the copyright and license notices in the minified version, we should keep it. If nothing else, to make sure our downstream can more easily comply with the license of our code.

But, unless I’m mistaken, _1)_ this repo includes (or at least depends on) 3rd party code, and _2)_ going with LGPL-2.1-or-later would in fact be a license change for at least part of the code, which seems to be under MIT so far. If so, I would need to dig in a bit more. But it doesn’t look like a complex beast :)
