### ISSUE TITLE
Themelet with version set to any doesn't appear in globally installed npm modules

### ISSUE THREAD

**Issue by mwilliams2014** [liferay/liferay-js-themes-toolkit#490]
Steps to reproduce:
1. Create a themelet with `yo liferay-theme:themelet` and set the version to `Any`.
2. Run `npm link` to globally install the Themelet.
3. Navigate to a Theme and extend it with `npm run extend`.
4. Select `Themelet` to extend and choose `Search globally installed npm modules (development purposes only)`.

Expected: The Themelet is available to extend
Result: The Themelet doesn't appear in the List

Version tested: generator-liferay-theme@10.0.0

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
