### ISSUE TITLE
Support SVG processing

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#50]
Based on [Add svg processing into the build](https://github.com/liferay/liferay-theme-tasks/issues/36) by @mir333, this is a long-standing request.

We need to add support to customizing and adding additional svgs to our build process.

/cc @pat270, any special requests for this?

**Comment by pat270** [comment]
@jbalsas No special requests. I was thinking it would be a directory with custom icons and appending to `icons.svg`?

**Comment by wincent** [comment]
We've just migrated this project to [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects) in the name of consolidation. As this issue is quite old now, I'm not going to transfer it automatically. If you consider it to be still relevant, please [create a fresh issue over in the new repo](https://github.com/liferay/liferay-frontend-projects/issues/new?labels=js-themes-toolkit&template=js-themes-toolkit.md).
