### ISSUE TITLE
Limitations of Styled theme and usage of Classic

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-themes-toolkit#90]
Hi everyone!

For a long time, usage of the `Classic` theme as a starting point has been discouraged. We keep seeing this question pop up from time to time, so we're looking for feedback on current usage and limitations of the `Styled` theme and reasons to start from `Classic`.

Some answers we're looking for are:
- What type of themes are you building on top of `Styled` (if any)?
- What type of themes are you building on top of `Classic` (if any)?
    - How many additions/overrides/resets are you applying?
    - How are you managing changes in the upstream theme?
- What specific things do you need from `Classic` that's lacking in `Styled`?
    - Is it a default template for navigation?
    - Is it the color scheme?
    - ...

Waiting to hear from you!

Thanks!

**Comment by caneta** [comment]
> For a long time, usage of the `Classic` theme as a starting point has been discouraged. We keep seeing this question pop up from time to time, so we're looking for feedback on current usage and limitations of the `Styled` theme and reasons to start from `Classic`.

I don't think starting from **styled** has some kind of limitation: I use it 99% of the times I create a new theme and I'm ok with that.

>     * What type of themes are you building on top of `Styled` (if any)?

Every theme I create for customers: it's a valid starting point to create my own css, js and templates.

>     * What type of themes are you building on top of `Classic` (if any)?

Only for study purposes: I would like to have a comfortable way to have a classic theme starting point to understand how this is build and how I can modify it.
       
>       * How many additions/overrides/resets are you applying?

For styled themes, I rewrite a lot of templates (`portal_normal.ftl`, `navigation.ftl`, `portlet.ftl`) and I add almost everything inside the css and js directories. Usually, I use `_custom.scss` to import everything and I overwrite `main.js` as described above

>       * How are you managing changes in the upstream theme?

 Usually I copy files I need to overwrite from the build directory after a `gulp build` into my src directory.

>     * What specific things do you need from `Classic` that's lacking in `Styled`?

Nothing in particular.

**Comment by ferdez** [comment]
IMHO I think the default liferay theme should be loaded with structures and templates to create essential widgets like carousels, photo galleries, embedded videos, geotagged content, etc. 

For many years now, the main disappointment we have when installing a fresh liferay is how much work you still have to do afterwards to build a simple website with a modern look.  

Marcos Castro has been doing an excellent job with theme samples but it's not bundled with the distribution.

HTH

**Comment by severinrohner** [comment]
My starting point is the classic theme, but I remove/change a lot from the classic stuff, because the css use:
- many id's
- px instead of %, rem or em
- strong selectors with many classes (nesting in scss)
- less variables

From the classic I use the JS for login in popup.
The styles are more a starting point and a change it to my needs, mostly because the reasons above and because the needs of the current design.

Mostly I change a lot in a theme, fonts, colors, button style, breakpoints, grid, ...
Sometimes it's very hard, because if I change a global Liferay variable or add global styles to have a own font in the whole portal, a lot of Liferay stuff will be broken. IMHO, one reason is, that Liferay use a lot of px.

In the Liferay Lexicon are some helps how to change a theme, but for me this is to less. It would be useful to have a guid, which variable can be change, which not, or how to change the default theme. E.g. how can I change the look and Feel of my page without targeting the portlet configurations. 

I use own/modified template for nearly every thing. (portal_normal, navigation portlet, AssetPublisher, journal article, category navigation, ...)

We also add custom gulp task for css and js linter, this is very comfortable since Liferay 7.

**Comment by faragos** [comment]
We mainly used the styled version of the Liferay-Theme. One day we decided to do our own base-theme, because everytime we set up a new one we do stuff like: Adding linters, adding autoprefixer, removing unnecessary code, creating filestructure for CSS, adding some utils in the custom inits and so on. We took the styled as a base and added some parts for the classic one.
I think we took out the navigation styling.
I already had the idea to start with no Liferay styling, because stuff like styling every label or such strong selectors that you can only overwrite them when you have like 6 classes are kinda annoying.

The reason why I would take the styled again over the classic one is because you have to overwrite less and have more control.

**Comment by duracell80** [comment]
> What specific things do you need from `Classic` that's lacking in `Styled`?

A comprehensive "already there" series of variables so that I can change color schemes and make good use of SaSS without needing to run around and debug 300 partials. Again stuff should already be there, it should be developer friendly.

**Comment by duracell80** [comment]
Kill theme contributors. These are overkill. Bring that stuff back into the theme.

**Comment by jbalsas** [comment]
For anyone watching here... we know it's long overdue, but we're planning to work on some version of this prior to 7.3 (and likely backporting it to older versions of the toolkit).

I've created [Add support for "Classic" extend ](https://github.com/liferay/liferay-js-themes-toolkit/issues/419) to add the possibility to somehow get that look and feel out of the box quickly.

Please, head over there if you want to provide any additional feedback on the matter!

Thanks everyone for your participation! :)
